-- =========================================================
-- Unified Payments Platform Schema (v5)
-- Reference copy for the Payment Engine service. This is the
-- platform-wide schema (shared across GoMobi's payment services) - the
-- Payment Engine itself only reads/writes MERCHANT, SUB_MERCHANT,
-- PAYMENT_METHOD, PROVIDER_CONFIGURATION, PROVIDER_SUPPORTED_METHOD,
-- PAYMENT_TRANSACTION and QR_TRANSACTION_DETAILS. Settlement, IPN and QR
-- callback audit tables are included for completeness/FK context but are
-- owned and populated by other services (settlement batch job, gateway
-- layer) - this service does not write to them.
-- =========================================================

-- =========================================================
-- REFERENCE / MASTER TABLES
-- =========================================================
CREATE TABLE PAYMENT_METHOD(
 PAYMENT_METHOD_ID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 PAYMENT_METHOD_CODE VARCHAR(50) NOT NULL,          -- e.g. QRIS, DUITNOW_QR, VIETQR
 PAYMENT_METHOD_NAME VARCHAR(100) NOT NULL,
 PAYMENT_METHOD_TYPE ENUM('QR','CARD','E_WALLET','ONLINE_BANKING') NOT NULL,
 CHANNEL_CODE VARCHAR(50) NOT NULL,                 -- country-prefixed, matches API payment_method.channel_code e.g. MY_DUITNOW_QR
 STATUS ENUM('ACTIVE','INACTIVE') DEFAULT 'ACTIVE',
 CREATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 UPDATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 UNIQUE KEY UK_PAYMENT_METHOD_CODE(PAYMENT_METHOD_CODE),
 UNIQUE KEY UK_CHANNEL_CODE(CHANNEL_CODE),
 KEY IDX_PAYMENT_METHOD_TYPE(PAYMENT_METHOD_TYPE)
);

-- One row per external payment service (bank, e-wallet, or switch/acquirer)
-- the platform integrates with. A provider can support more than one
-- payment method; that relationship lives in PROVIDER_SUPPORTED_METHOD.
CREATE TABLE PROVIDER_CONFIGURATION(
 PROVIDER_CONFIGURATION_ID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 PROVIDER_CODE VARCHAR(50) NOT NULL,          -- e.g. GOPAY, OVO, MAYBANK, TNG, MOMO
 PROVIDER_NAME VARCHAR(150) NOT NULL,
 REGION_CODE VARCHAR(10),
 STATUS ENUM('ACTIVE','INACTIVE') DEFAULT 'ACTIVE',
 CREATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 UPDATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 UNIQUE KEY UK_PROVIDER_CODE(PROVIDER_CODE)
);

-- Many-to-many: which payment methods a given provider supports.
CREATE TABLE PROVIDER_SUPPORTED_METHOD(
 PROVIDER_SUPPORTED_METHOD_ID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 PROVIDER_CONFIGURATION_FK BIGINT UNSIGNED NOT NULL,
 PAYMENT_METHOD_FK BIGINT UNSIGNED NOT NULL,
 STATUS ENUM('ACTIVE','INACTIVE') DEFAULT 'ACTIVE',
 CREATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 UPDATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 UNIQUE KEY UK_PROVIDER_SUPPORTED_METHOD(PROVIDER_CONFIGURATION_FK, PAYMENT_METHOD_FK),
 KEY IDX_PSM_PAYMENT_METHOD(PAYMENT_METHOD_FK),
 CONSTRAINT FK_PSM_PROVIDER FOREIGN KEY(PROVIDER_CONFIGURATION_FK) REFERENCES PROVIDER_CONFIGURATION(PROVIDER_CONFIGURATION_ID),
 CONSTRAINT FK_PSM_METHOD FOREIGN KEY(PAYMENT_METHOD_FK) REFERENCES PAYMENT_METHOD(PAYMENT_METHOD_ID)
);

-- Host-side MDR: what each provider charges the platform per payment method.
CREATE TABLE PROVIDER_MDR_CONFIGURATION(
 PROVIDER_MDR_CONFIGURATION_ID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 PROVIDER_CONFIGURATION_FK BIGINT UNSIGNED NOT NULL,
 PAYMENT_METHOD_FK BIGINT UNSIGNED NOT NULL,
 MDR_FEE_TYPE ENUM('PERCENTAGE','FIXED') NOT NULL,
 MDR_FEE_VALUE DECIMAL(18,4) NOT NULL,
 VALID_FROM TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 VALID_TO TIMESTAMP NULL,
 IS_CURRENT TINYINT GENERATED ALWAYS AS (CASE WHEN VALID_TO IS NULL THEN 1 ELSE NULL END) STORED,
 STATUS ENUM('ACTIVE','INACTIVE') DEFAULT 'ACTIVE',
 CREATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 UPDATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 UNIQUE KEY UK_PROVIDER_MDR_CURRENT(PROVIDER_CONFIGURATION_FK, PAYMENT_METHOD_FK, IS_CURRENT),
 KEY IDX_PMC_PROVIDER(PROVIDER_CONFIGURATION_FK),
 KEY IDX_PMC_PAYMENT_METHOD(PAYMENT_METHOD_FK),
 KEY IDX_PMC_VALID_RANGE(VALID_FROM, VALID_TO),
 FOREIGN KEY(PROVIDER_CONFIGURATION_FK) REFERENCES PROVIDER_CONFIGURATION(PROVIDER_CONFIGURATION_ID),
 FOREIGN KEY(PAYMENT_METHOD_FK) REFERENCES PAYMENT_METHOD(PAYMENT_METHOD_ID)
);

CREATE TABLE MERCHANT(
 MERCHANT_ID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 MASTER_MID VARCHAR(50) NOT NULL,
 GLOBAL_ACCOUNT_ID VARCHAR(100) NOT NULL,     -- matches API global_account_id
 MERCHANT_NAME VARCHAR(150) NOT NULL,
 MERCHANT_CATEGORY ENUM('BE','PGE','PGBE') NOT NULL,
 STATUS ENUM('ACTIVE','INACTIVE','SUSPENDED','PENDING') DEFAULT 'ACTIVE',
 CREATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 UPDATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 UNIQUE KEY UK_MASTER_MID(MASTER_MID),
 KEY IDX_GLOBAL_ACCOUNT_ID(GLOBAL_ACCOUNT_ID)
);

CREATE TABLE SUB_MERCHANT(
 SUB_MERCHANT_ID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 MERCHANT_FK BIGINT UNSIGNED NOT NULL,
 SUB_MERCHANT_MID VARCHAR(50) NOT NULL,
 SUB_MERCHANT_NAME VARCHAR(150) NOT NULL,
 STATUS ENUM('ACTIVE','INACTIVE') DEFAULT 'ACTIVE',
 CREATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 UPDATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 UNIQUE KEY UK_SUB_MERCHANT_MID(SUB_MERCHANT_MID),
 KEY IDX_SUB_MERCHANT(MERCHANT_FK),
 CONSTRAINT FK_SUB_MERCHANT FOREIGN KEY(MERCHANT_FK) REFERENCES MERCHANT(MERCHANT_ID)
);

-- =========================================================
-- PAYMENT_TRANSACTION -- business fields + (for now) QR processing fields
-- idempotency -- a merchant cannot submit the same reference twice.
--
-- v5 CHANGES:
--  - Removed MERCHANT_NAME_SNAPSHOT / SUB_MERCHANT_NAME_SNAPSHOT
--    (names are resolvable via MERCHANT_FK / SUB_MERCHANT_FK; no longer
--    denormalized here. Reinstate if point-in-time name freezing is
--    actually required for audit/compliance reasons.)
--  - Added GATEWAY_IDEMPOTENCY_KEY, scoped unique per merchant
--    (assumption: key is caller-supplied like Stripe's Idempotency-Key
--    header, scoped to the submitting merchant -- flag if this should
--    instead be globally unique).
-- =========================================================
CREATE TABLE PAYMENT_TRANSACTION(
 PAYMENT_TRANSACTION_ID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 TRANSACTION_ID VARCHAR(150) NOT NULL,        -- mobi-generated transaction id; API response `transaction_id`
 MERCHANT_REF_NO VARCHAR(150) NOT NULL,       -- API request/response `reference_id`
 GATEWAY_IDEMPOTENCY_KEY VARCHAR(150) NOT NULL, -- idempotency key from gateway layer, scoped per merchant
 RRN VARCHAR(50),            -- RRN (interbank trace number)
 PSP_REF_NO VARCHAR(150),                     -- PSP-side reference; used for lookup/reconciliation/support
 TRANSACTION_STATUS ENUM('INITIATED','PENDING','SUCCESS','FAILED') NOT NULL,
 PROVIDER_CONFIGURATION_FK BIGINT UNSIGNED NOT NULL,
 MERCHANT_FK BIGINT UNSIGNED NOT NULL,
 SUB_MERCHANT_FK BIGINT UNSIGNED,
 PAYMENT_METHOD_FK BIGINT UNSIGNED NOT NULL,
 TRANSACTION_AMOUNT DECIMAL(18,2) NOT NULL,
 CURRENCY_CODE CHAR(3) NOT NULL,
 CREATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 UPDATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PAID_TIMESTAMP TIMESTAMP NULL,
 UNIQUE KEY UK_TRANSACTION_ID(TRANSACTION_ID),
 UNIQUE KEY UK_MERCHANT_REF(MERCHANT_FK, MERCHANT_REF_NO),
 UNIQUE KEY UK_MERCHANT_IDEMPOTENCY_KEY(MERCHANT_FK, GATEWAY_IDEMPOTENCY_KEY),
 KEY IDX_PAYMENT_PROVIDER_CONFIG(PROVIDER_CONFIGURATION_FK),
 KEY IDX_PAYMENT_MERCHANT(MERCHANT_FK),
 KEY IDX_PAYMENT_SUBMERCHANT(SUB_MERCHANT_FK),
 KEY IDX_PAYMENT_METHOD(PAYMENT_METHOD_FK),
 KEY IDX_STATUS_CREATED(TRANSACTION_STATUS,CREATED_TIMESTAMP),
 KEY IDX_METHOD_CREATED(PAYMENT_METHOD_FK,CREATED_TIMESTAMP),
 KEY IDX_PSP_REF(PSP_REF_NO),
 KEY IDX_RRN(RRN),
 KEY IDX_TRANSACTION_ID_STATUS(TRANSACTION_ID, TRANSACTION_STATUS),
 KEY IDX_PROVIDER_STATUS(PROVIDER_CONFIGURATION_FK, TRANSACTION_STATUS),
 KEY IDX_CREATED_PAID(CREATED_TIMESTAMP, PAID_TIMESTAMP),
 CONSTRAINT FK_PT_PROVIDER_CONFIG FOREIGN KEY(PROVIDER_CONFIGURATION_FK) REFERENCES PROVIDER_CONFIGURATION(PROVIDER_CONFIGURATION_ID),
 CONSTRAINT FK_PT_MERCHANT FOREIGN KEY(MERCHANT_FK) REFERENCES MERCHANT(MERCHANT_ID),
 CONSTRAINT FK_PT_SUB FOREIGN KEY(SUB_MERCHANT_FK) REFERENCES SUB_MERCHANT(SUB_MERCHANT_ID),
 CONSTRAINT FK_PT_PM FOREIGN KEY(PAYMENT_METHOD_FK) REFERENCES PAYMENT_METHOD(PAYMENT_METHOD_ID)
);


-- =========================================================
-- QR_TRANSACTION_DETAILS -- QR code + customer data
-- =========================================================
CREATE TABLE QR_TRANSACTION_DETAILS(
 QR_TRANSACTION_DETAIL_ID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 PAYMENT_TRANSACTION_FK BIGINT UNSIGNED NOT NULL,
 QR_TYPE ENUM('STATIC','DYNAMIC') NOT NULL,
 QR_MODE ENUM('MERCHANT_PRESENTED','CONSUMER_PRESENTED') NOT NULL DEFAULT 'MERCHANT_PRESENTED',
 QR_IMAGE_URL VARCHAR(1000),
 MERCHANT_CATEGORY_CODE VARCHAR(4),
 MERCHANT_CITY VARCHAR(100),
 COUNTRY_CODE CHAR(2),
 QR_EXPIRY_TIMESTAMP TIMESTAMP NULL,
 CUSTOMER_ID VARCHAR(100),                    -- merchant-supplied customer id; API customer.id
 CUSTOMER_NAME VARCHAR(150),
 CUSTOMER_EMAIL VARCHAR(150),
 CUSTOMER_PHONE VARCHAR(50),
 CUSTOMER_ACCOUNT_MASKED VARCHAR(50),
 METADATA JSON,                               -- merchant-defined, opaque, echoed back as-is via API metadata
 CREATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 UPDATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 UNIQUE KEY UK_QR_DETAILS_TXN(PAYMENT_TRANSACTION_FK),
 KEY IDX_QR_CUSTOMER_ID(CUSTOMER_ID),
 CONSTRAINT FK_QRD_PT FOREIGN KEY(PAYMENT_TRANSACTION_FK) REFERENCES PAYMENT_TRANSACTION(PAYMENT_TRANSACTION_ID)
);

-- Verbatim record of every inbound provider callback (payment notification,
-- status update, refund, reversal, settlement). Owned/populated by the
-- gateway layer - NOT by the Payment Engine service.
CREATE TABLE QR_CALLBACK_AUDIT(
 QR_CALLBACK_AUDIT_ID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 PAYMENT_TRANSACTION_FK BIGINT UNSIGNED NOT NULL,
 CALLBACK_TYPE ENUM('PAYMENT_NOTIFICATION','STATUS_UPDATE','REFUND','REVERSAL','SETTLEMENT') NOT NULL,
 REQUEST_HEADERS JSON,
 REQUEST_BODY JSON,
 RECEIVED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 PROCESSED_FLAG BOOLEAN DEFAULT FALSE,
 PROCESS_RESULT ENUM('SUCCESS','FAILED','DUPLICATE','IGNORED','INVALID_SIGNATURE','VALIDATION_FAILED'),
 HTTP_STATUS INT,
 RETRY_COUNT INT DEFAULT 0,
 CREATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 KEY IDX_QCA_PAYMENT_TRANSACTION(PAYMENT_TRANSACTION_FK),
 KEY IDX_QCA_RECEIVED_TIMESTAMP(RECEIVED_TIMESTAMP),
 KEY IDX_QCA_PROCESSED_FLAG(PROCESSED_FLAG),
 KEY IDX_QCA_CALLBACK_TYPE(CALLBACK_TYPE),
 CONSTRAINT FK_QCA_PT FOREIGN KEY(PAYMENT_TRANSACTION_FK) REFERENCES PAYMENT_TRANSACTION(PAYMENT_TRANSACTION_ID)
);

-- =========================================================
-- SETTLEMENT
-- =========================================================
CREATE TABLE SETTLEMENT_CONFIGURATION(
 SETTLEMENT_CONFIGURATION_ID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 MERCHANT_FK BIGINT UNSIGNED NOT NULL,
 PROVIDER_CONFIGURATION_FK BIGINT UNSIGNED NULL,      -- NULL = applies across all providers for this method
 PAYMENT_METHOD_FK BIGINT UNSIGNED NOT NULL,
 PROVIDER_KEY BIGINT UNSIGNED GENERATED ALWAYS AS (COALESCE(PROVIDER_CONFIGURATION_FK, 0)) STORED,
 SETTLEMENT_TYPE VARCHAR(50),
 MDR_FEE_TYPE ENUM('PERCENTAGE','FIXED'),
 MDR_FEE_VALUE DECIMAL(18,4),
 STATUS ENUM('ACTIVE','INACTIVE') DEFAULT 'ACTIVE',
 CREATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 UPDATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 UNIQUE KEY UK_SETTLEMENT(MERCHANT_FK,PROVIDER_KEY,PAYMENT_METHOD_FK,SETTLEMENT_TYPE),
 KEY IDX_SC_PROVIDER(PROVIDER_CONFIGURATION_FK),
 FOREIGN KEY(MERCHANT_FK) REFERENCES MERCHANT(MERCHANT_ID),
 FOREIGN KEY(PROVIDER_CONFIGURATION_FK) REFERENCES PROVIDER_CONFIGURATION(PROVIDER_CONFIGURATION_ID),
 FOREIGN KEY(PAYMENT_METHOD_FK) REFERENCES PAYMENT_METHOD(PAYMENT_METHOD_ID)
);

CREATE TABLE TRANSACTION_SETTLEMENT(
 TRANSACTION_SETTLEMENT_ID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 PAYMENT_TRANSACTION_FK BIGINT UNSIGNED NOT NULL,
 SETTLEMENT_CONFIGURATION_FK BIGINT UNSIGNED,
 HOST_REF_NO VARCHAR(150),                    -- host/switch-side settlement reference
 TRANSACTION_AMOUNT DECIMAL(18,2),
 MDR_FEE_TYPE ENUM('PERCENTAGE','FIXED'),
 MDR_FEE_VALUE DECIMAL(18,4),
 MDR_AMOUNT DECIMAL(18,2),
 HOST_MDR_AMOUNT DECIMAL(18,2),
 NET_SETTLEMENT_AMOUNT DECIMAL(18,2),
 SETTLEMENT_DATE DATE,
 SETTLEMENT_STATUS ENUM('PENDING','PROCESSING','SETTLED','FAILED'),
 CREATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 UPDATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 KEY IDX_SETTLEMENT_DATE_STATUS(SETTLEMENT_DATE, SETTLEMENT_STATUS),
 KEY IDX_TS_HOST_REF(HOST_REF_NO),
 FOREIGN KEY(PAYMENT_TRANSACTION_FK) REFERENCES PAYMENT_TRANSACTION(PAYMENT_TRANSACTION_ID),
 FOREIGN KEY(SETTLEMENT_CONFIGURATION_FK) REFERENCES SETTLEMENT_CONFIGURATION(SETTLEMENT_CONFIGURATION_ID)
);

-- =========================================================
-- IPN -- the platform's own OUTBOUND notifications to merchants.
-- Owned/populated by the gateway layer - NOT by the Payment Engine service.
-- =========================================================
CREATE TABLE IPN_CONFIGURATION(
 IPN_CONFIGURATION_ID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 MERCHANT_FK BIGINT UNSIGNED NOT NULL,
 PAYMENT_METHOD_FK BIGINT UNSIGNED NOT NULL,
 IPN_URL VARCHAR(1000),
 REDIRECT_URL VARCHAR(1000),
 IPN_METHOD ENUM('POST','PUT') DEFAULT 'POST',
 RETRY_COUNT INT DEFAULT 0,
 RETRY_INTERVAL_SECONDS INT DEFAULT 60,
 VALID_FROM TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 VALID_TO TIMESTAMP NULL,
 IS_ACTIVE BOOLEAN DEFAULT TRUE,
 ACTIVE_KEY TINYINT GENERATED ALWAYS AS (CASE WHEN IS_ACTIVE = TRUE THEN 1 ELSE NULL END) STORED,
 STATUS ENUM('ACTIVE','INACTIVE') DEFAULT 'ACTIVE',
 CREATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 UPDATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 UNIQUE KEY UK_IPN(MERCHANT_FK,PAYMENT_METHOD_FK,ACTIVE_KEY),
 FOREIGN KEY(MERCHANT_FK) REFERENCES MERCHANT(MERCHANT_ID),
 FOREIGN KEY(PAYMENT_METHOD_FK) REFERENCES PAYMENT_METHOD(PAYMENT_METHOD_ID)
);

CREATE TABLE TRANSACTION_IPN_AUDIT(
 TRANSACTION_IPN_AUDIT_ID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 PAYMENT_TRANSACTION_FK BIGINT UNSIGNED NOT NULL,
 IPN_CONFIGURATION_FK BIGINT UNSIGNED,
 EVENT_TYPE VARCHAR(50),
 REQUEST_PAYLOAD JSON,
 RESPONSE_PAYLOAD JSON,
 RESPONSE_HTTP_STATUS INT,
 RETRY_ATTEMPT INT DEFAULT 0,
 DELIVERY_STATUS ENUM('PENDING','SUCCESS','FAILED'),
 PROCESSED_FLAG BOOLEAN DEFAULT FALSE,
 MERCHANT_ACK_TIMESTAMP TIMESTAMP NULL,       -- when merchant endpoint acked this attempt
 CREATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 UPDATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY(PAYMENT_TRANSACTION_FK) REFERENCES PAYMENT_TRANSACTION(PAYMENT_TRANSACTION_ID),
 FOREIGN KEY(IPN_CONFIGURATION_FK) REFERENCES IPN_CONFIGURATION(IPN_CONFIGURATION_ID)
);

-- =========================================================
-- Seed data (matches application-dev.yml defaults / demo Postman request)
-- =========================================================
INSERT INTO PAYMENT_METHOD (PAYMENT_METHOD_CODE, PAYMENT_METHOD_NAME, PAYMENT_METHOD_TYPE, CHANNEL_CODE) VALUES
 ('QRIS', 'QRIS (Indonesia)', 'QR', 'ID_QRIS'),
 ('DUITNOW_QR', 'DuitNow QR (Malaysia)', 'QR', 'MY_DUITNOW_QR'),
 ('VIETQR', 'VietQR (Vietnam)', 'QR', 'VN_VIETQR');

INSERT INTO PROVIDER_CONFIGURATION (PROVIDER_CODE, PROVIDER_NAME, REGION_CODE, STATUS) VALUES
 ('GOPAY', 'GoPay', 'ID', 'ACTIVE'),
 ('OVO', 'OVO', 'ID', 'ACTIVE'),
 ('MAYBANK', 'Maybank', 'MY', 'ACTIVE'),
 ('TNG', "Touch 'n Go eWallet", 'MY', 'ACTIVE'),
 ('PAYOK', 'Pay Ok', 'VN', 'ACTIVE');

INSERT INTO PROVIDER_SUPPORTED_METHOD (PROVIDER_CONFIGURATION_FK, PAYMENT_METHOD_FK, STATUS) VALUES
 ((SELECT PROVIDER_CONFIGURATION_ID FROM PROVIDER_CONFIGURATION WHERE PROVIDER_CODE='GOPAY'), (SELECT PAYMENT_METHOD_ID FROM PAYMENT_METHOD WHERE PAYMENT_METHOD_CODE='QRIS'), 'ACTIVE'),
 ((SELECT PROVIDER_CONFIGURATION_ID FROM PROVIDER_CONFIGURATION WHERE PROVIDER_CODE='OVO'), (SELECT PAYMENT_METHOD_ID FROM PAYMENT_METHOD WHERE PAYMENT_METHOD_CODE='QRIS'), 'ACTIVE'),
 ((SELECT PROVIDER_CONFIGURATION_ID FROM PROVIDER_CONFIGURATION WHERE PROVIDER_CODE='MAYBANK'), (SELECT PAYMENT_METHOD_ID FROM PAYMENT_METHOD WHERE PAYMENT_METHOD_CODE='DUITNOW_QR'), 'ACTIVE'),
 ((SELECT PROVIDER_CONFIGURATION_ID FROM PROVIDER_CONFIGURATION WHERE PROVIDER_CODE='TNG'), (SELECT PAYMENT_METHOD_ID FROM PAYMENT_METHOD WHERE PAYMENT_METHOD_CODE='DUITNOW_QR'), 'ACTIVE'),
 ((SELECT PROVIDER_CONFIGURATION_ID FROM PROVIDER_CONFIGURATION WHERE PROVIDER_CODE='PAYOK'), (SELECT PAYMENT_METHOD_ID FROM PAYMENT_METHOD WHERE PAYMENT_METHOD_CODE='VIETQR'), 'ACTIVE');

-- Demo merchant/sub-merchant matching the sample Create Payment Postman request.
INSERT INTO MERCHANT (MASTER_MID, GLOBAL_ACCOUNT_ID, MERCHANT_NAME, MERCHANT_CATEGORY, STATUS) VALUES
 ('MID000001', 'GA000001', 'Demo Merchant Pte Ltd', 'PGE', 'ACTIVE');

INSERT INTO SUB_MERCHANT (MERCHANT_FK, SUB_MERCHANT_MID, SUB_MERCHANT_NAME, STATUS) VALUES
 ((SELECT MERCHANT_ID FROM MERCHANT WHERE MASTER_MID='MID000001'), 'SUB000001', 'Demo Merchant - HN01', 'ACTIVE');
